### ISSUE TITLE
CUDA cmake module deprecated

### ISSUE THREAD

**Issue by Thodoris1999** [ACDSLab/MPPI-Generic#19]
cmake 3.27 deprecated the CUDA package, so this project does not build in newer cmake versions. This is unfortunate because upgrading to using `FindCUDAToolkit` requires minimum version 3.17, only released 5 years ago (for example Ubuntu 20 uses 3.16).

What do you think? Switch to new CUDA library finding method and drop support for old cmake versions? Or use ifs to choose between the two?

Either way I can help since I had to make some of the changes for this to work on my machine

**Comment by bogidude** [comment]
I think I have this solved on a private branch already. It also makes some other CMake adjustments (adding some compilation options and renaming others). Let me put those up publicly and if you have the time, you can see if it works for you as well

**Comment by bogidude** [comment]
The branch with updated CMake should be at [feature/update_cmake_configuration](https://github.com/ACDSLab/MPPI-Generic/tree/feature/update_cmake_configuration). Try it out and let me know if you have any questions/comments.

**Comment by bogidude** [comment]
I can't reproduce these results. The branch [feature/update_cmake_configuration](https://github.com/ACDSLab/MPPI-Generic/tree/feature/update_cmake_configuration) does not compile on CUDA 12.6 (with the same unsupported float variant error we started #17 with) as it branched off from before I made the other fixes. However, if I do a local merge of this branch and `main`, I can compile just fine. I would try completely deleting the build folder (not just `make clean`) as CMake can cache things in a weird fashion and the errors you are seeing remind of times I have needed to delete the build folder.

Can you try the following on your system and see if it works?
```bash
git checkout feature/update_cmake_configuration
# Create a temp merge branch of the CMake changes and the main branch
git checkout -b tmp_merge/cmake_and_main 
git merge origin/main
# Delete the contents of the build folder
rm -rf ./build/*
cd build
# Recompile from scratch
cmake ../ -DMPPI_BUILD_EXAMPLES=ON
make cartpole_mppi # This target was failing to build in your errs.txt
```

**Comment by Thodoris1999** [comment]
I just got a hint. Compiling with c++ standard 14 or higher works. By default cmake is manually specifying -std=c++11, not sure why that happens. Normally I thought cmake does not specify a standard which makes gcc use c++17 (in newer versions).

[cmake - requiring language standards](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards)
```cmake
target_compile_features(${MPPI_HEADER_LIBRARY_NAME} INTERFACE cxx_std_14)
```

**Comment by bogidude** [comment]
There are probably some unforeseen reasons as to why Eigen might have to take a different approach.

Have you tried compiling the godbolt example code locally on your system yet? It would give us an idea of whether or not this is an issue with Eigen or with the MPPI library instead.

**Comment by Thodoris1999** [comment]
Hmm, it does compile with both
`g++ -std=c++11 -I/usr/include/eigen3 test.cpp -o test`
and
`g++ -std=c++17 -I/usr/include/eigen3 test.cpp -o test`

**Comment by Thodoris1999** [comment]
Same with
`nvcc -std=c++11 -I/usr/include/eigen3 test.cpp -o test`
and
`nvcc -std=c++17 -I/usr/include/eigen3 test.cpp -o test`

**Comment by bogidude** [comment]
Hmm, so there looks to be some issue with how our library is interfacing with all of this. I am not sure how to handle this at the moment. From my testing, I can't reproduce the compilation errors (CUDA versions up to 12.6.3 and gcc versions up to 13 seem to compile fine) and I also don't want to up the minimum C++ standard of the library itself as preserving compatibility with older systems is important to me. I could maybe set up different default C++ standards depending on something though it is not clear what to use as the signal to switch from C++11 to C++14 even is. I think I will have to spend the time to upgrade my NVIDIA drivers so I can try to run a newer gcc and CUDA versions and hopefully get the same compilation issues and debug from there.

**Comment by Thodoris1999** [comment]
I appreciate taking time to look at this.

If the standard is left unspecified, would those old systems automatically fall back to a standard they support (e.g. c++11)?

**Comment by Thodoris1999** [comment]
Correct

**Comment by bogidude** [comment]
Ok I have now tested the following setup and instructions in a  docker container:
- Ubuntu 24.04
- CUDA 12.9.1
- gcc/g++ 14.2
- Eigen 3.4.0

```bash
git checkout feature/update_cmake_configuration
# Create a temp merge branch of the CMake changes and the main branch
git checkout -b tmp_merge/cmake_and_main 
git merge origin/main
# Delete the contents of the build folder
rm -rf ./build/*
cd build
# Recompile from scratch
cmake ../ -DMPPI_BUILD_EXAMPLES=ON
make
```
Everything compiles and the only CMake warning is coming from our cnpy submodule that I still need to update to a newer CMake version minimum. I think the compilation errors you are seeing are from some weird mixture of library versions in Arch Linux that I can't test unfortunately.

**Comment by Thodoris1999** [comment]
Good news is that it at least works on Ubuntu 24 (with gcc 13.3). It could be due to some change in gcc between 13.3 and 14.3.1.
